name: notepadqq # check to see if it's available
version: '1.2.0+git' # check the version number of notepadqq's packages
summary: Notepadqq is a Notepad++-like editor for the Linux desktop. # 79 char long summary
description: |
  It helps developers by providing all you can expect from a general purpose text editor, such as syntax highlighting for more than 100 different languages, code folding, color schemes, file monitoring, multiple selection and much more.
  You can search text using the power of regular expressions. You can organize documents side by side. You can use real-time highlighting to find near identifiers in no time.
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs
  
apps:
  notepadqq: 
    command: desktop-launch $SNAP/usr/local/lib/notepadqq/notepadqq-bin
    desktop: usr/local/share/applications/notepadqq.desktop
    plugs:
      - desktop
      - home
      - opengl
      - unity7
      - x11
      - gsettings
      - optical-drive
      - removable-media
      - media-hub

parts:
  my-part:
    # See 'snapcraft plugins'
    build-packages:

      - qtbase5-dev
      - libqt5webkit5-dev
      - libqt5svg5-dev
      - qttools5-dev-tools
      
      
    stage-packages: 
      
      - qtbase5-dev      
      - libqt5webkit5-dev
      - libqt5svg5-dev
      - coreutils

    source-type: git
    source: https://github.com/notepadqq/notepadqq
    after: [desktop-qt5] 
    plugin: qmake
    # configflags:
    #  - --prefix=$SNAPCRAFT_PART_INSTALL/usr

    
